# Generated by Django 5.0 on 2024-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
